"""AMReX printers driven by a frozen :class:`SystemModel`.

The committed C++ driver (``Source/make_rhs.H`` + ``Source/ZoomyAmr.cpp``) calls a
fixed set of ``Model::`` and ``Numerics::`` device functions.  The convective
flux / non-conservative product live entirely inside ``Numerics.H`` (generated by
``zoomy_core``'s already-working ``AmrexNumerics``), so the ``Model.H`` side only
needs the *source / jacobians / aux-update / eigenvalue / boundary* kernels plus a
handful of stubs so the translation units compile unchanged.

Design notes
------------
* We reuse :class:`zoomy_core.transformation.to_amrex.AmrexCore` (syntax mixin:
  ``amrex::SmallMatrix`` types, ``AMREX_GPU_*`` macros, ``Math::powi`` powers) and
  :class:`zoomy_core.transformation.generic_c.GenericCppBase` (CSE-based body
  generation, Piecewise → if/else).  We do **not** use ``GenericCppModel`` /
  ``AmrexModel`` (the Model-path), which is bit-rotted: current ``SME``/``SWE``
  expose neither ``gradient_variables`` nor ``_boundary_conditions`` — those moved
  onto the SystemModel.  Foam handled this with ``FoamSystemModelPrinter``; this
  is the AMReX analogue.
* Placeholder ("kernel") functions are mapped in :attr:`c_functions`, extending
  the base C map (``conditional``/``Min``/``Max``/``Abs``/``clamp_*``/
  ``max_wavespeed``) with the opaque kernels ``eigensystem`` / ``compute_derivative``
  routed to hand-written helpers in ``UserFunctions.H`` — the same opaque-call
  pattern foam uses (``to_openfoam.py``).
"""

import functools

import sympy as sp

from zoomy_core.transformation.generic_c import GenericCppBase
from zoomy_core.transformation.to_amrex import AmrexCore, AmrexNumerics

# Re-export the working core numerics printer under a local, intention-revealing
# name.  It already consumes a Riemann ``Numerics`` built over a SystemModel.
AmrexNumericsPrinter = AmrexNumerics


def _emit_user_call(name):
    """Return a ``c_functions`` lambda that prints ``amrex_user::<name>(args...)``
    — an opaque call resolved by the hand-written ``UserFunctions.H`` helper."""

    def _printer(p, *args):
        return f"amrex_user::{name}({', '.join(p.doprint(a) for a in args)})"

    return _printer


class AmrexSystemModelPrinter(AmrexCore, GenericCppBase):
    """Emit ``Model.H`` from a frozen :class:`SystemModel`."""

    _wrapper_name = "Model"
    _is_template_class = False
    gpu_enabled = True

    # Placeholder-function map: base C kernels + the opaque ones (foam parity).
    c_functions = {
        **GenericCppBase.c_functions,
        "eigensystem": _emit_user_call("eigensystem"),
        "compute_derivative": _emit_user_call("compute_derivative"),
    }

    def __init__(self, sm, *, analytical_eigenvalues=True):
        super().__init__()
        self.sm = sm
        self.model = sm  # AmrexCore signature helpers read ``self.model.*``
        self.analytical_eigenvalues = analytical_eigenvalues
        self.n_eq = len(sm.state)
        self.n_aux = len(sm.aux_state)
        self.dim = int(sm.dimension)
        self.n_param = len(list(sm.parameters.keys()))
        # Symbol → accessor maps (order matters: most specific first is fine since
        # the symbol sets are disjoint).
        self.register_map("Q", list(sm.state))
        self.register_map("Qaux", list(sm.aux_state))
        self.register_map("n", list(sm.normal.values()))
        self.register_map("p", list(sm.parameters.values()))

    # ── type / signature helpers ────────────────────────────────────────────
    def _t(self, n):
        return self.get_array_type((n,))

    def _args(self, *names):
        tbl = {
            "Q": f"{self._t(self.n_eq)} const& Q",
            "Qaux": f"{self._t(self.n_aux)} const& Qaux",
            "p": f"{self._t(self.n_param)} const& p",
            "n": f"{self._t(self.dim)} const& n",
            "X": f"{self._t(3)} const& X",
            "gradQ": f"{self._t(self.n_eq * self.dim)} const& gradQ",
            "time": "amrex::Real const time",
            "dX": "amrex::Real const dX",
            "bc_idx": "const int bc_idx",
        }
        return ",\n        ".join(tbl[a] for a in names)

    def _kernel(self, name, expr, shape, argnames):
        body = self.convert_expression_body(expr, shape)
        return self.wrap_function_signature(name, self._args(*argnames), body, shape)

    # ── expression builders ─────────────────────────────────────────────────
    def _vec(self, elements):
        return sp.Array(list(elements)).reshape(len(elements), 1)

    def _zeros(self, n):
        return self._vec([sp.Integer(0)] * n)

    def _identity_flat(self, n):
        return self._vec([sp.Integer(1) if r == c else sp.Integer(0)
                          for r in range(n) for c in range(n)])

    def _flatten_dir_major(self, arr, n_rows):
        """Flatten an (n_rows, ..., dim) tensor in dir-major order to a column."""
        flat = [arr[(*idx, d)]
                for d in range(self.dim)
                for idx in self._row_indices(arr, n_rows)]
        return self._vec(flat)

    def _row_indices(self, arr, n_rows):
        import itertools
        inner = arr.shape[:-1]  # drop the trailing dim axis
        return list(itertools.product(*(range(s) for s in inner)))

    # ── per-slot expressions, falling back to stubs when sm lacks a slot ─────
    def _expr_flux(self):
        f = self.sm.flux  # (n_eq, dim)
        flat = [f[i, d] for d in range(self.dim) for i in range(self.n_eq)]
        return self._vec(flat), self.n_eq * self.dim

    def _expr_matrix(self, mat):
        # (n_eq, n_state, dim) -> dir-major flat (dim * n_eq * n_state)
        flat = [mat[i, j, d]
                for d in range(self.dim)
                for i in range(self.n_eq)
                for j in range(self.n_eq)]
        return self._vec(flat), self.dim * self.n_eq * self.n_eq

    def _expr_source(self):
        s = self.sm.source
        return self._vec([s[i, 0] for i in range(self.n_eq)]), self.n_eq

    def _expr_eigenvalues(self):
        e = self.sm.eigenvalues
        return self._vec([e[i, 0] for i in range(self.n_eq)]), self.n_eq

    def _expr_source_jac(self):
        J = self.sm.source_jacobian  # (n_eq, n_eq)
        return self._vec([J[r, c] for r in range(self.n_eq)
                          for c in range(self.n_eq)]), self.n_eq * self.n_eq

    def _expr_update_aux(self):
        ua = getattr(self.sm, "update_aux_variables", None)
        if ua is None:
            # identity: return Qaux unchanged
            return self._vec(list(self.sm.aux_state)), self.n_aux
        return self._vec([ua[i, 0] for i in range(self.n_aux)]), self.n_aux

    def _bc_definition(self, attr):
        """Return the Piecewise body of a SystemModel BC ``Function`` slot."""
        fn = getattr(self.sm, attr, None)
        if fn is None:
            return None
        # The framework BC slot is a custom sp.Function carrying ``.definition``
        # (a nested array / Piecewise).  Fall back to the function's single arg.
        defn = getattr(fn, "definition", None)
        if defn is None and getattr(fn, "args", None):
            defn = fn
        return defn

    # ── header / footer ─────────────────────────────────────────────────────
    def get_includes(self):
        return ('#include <AMReX_Array4.H>\n'
                '#include <AMReX_Vector.H>\n'
                '#include <AMReX_SmallMatrix.H>')

    def _file_header(self, bc_tags):
        p_names = ", ".join(f'"{k}"' for k in self.sm.parameters.keys())
        p_vals = ", ".join(str(v) for v in self.sm.parameter_values.values())
        bc_str = ", ".join(f'"{t}"' for t in bc_tags)
        L = [
            "#pragma once",
            self.get_includes(),
            "#include <vector>",
            "#include <string>",
            "#include <algorithm>",
            "",
            "#ifdef __CUDACC__",
            "#define PORTABLE_FN __host__ __device__",
            "#else",
            "#define PORTABLE_FN",
            "#endif",
            "",
            '#include "UserFunctions.H"',
            "",
            "struct Model {",
            "    using T = amrex::Real;",
            f"    static constexpr int n_dof_q    = {self.n_eq};",
            f"    static constexpr int n_dof_qaux = {self.n_aux};",
            f"    static constexpr int n_parameters = {self.n_param};",
            f"    static constexpr int dimension  = {self.dim};",
            f"    static constexpr int n_dof_gradQ = {self.n_eq * self.dim};",
            "    static constexpr bool has_diffusion = false;",
            f"    static constexpr int n_boundary_tags = {len(bc_tags)};",
            f"    static const std::vector<std::string> get_boundary_tags() {{ return {{ {bc_str} }}; }}",
            f"    static const std::vector<std::string> parameter_names() {{ return {{ {p_names} }}; }}",
            f"    static const std::vector<T> default_parameters() {{ return {{ {p_vals} }}; }}",
        ]
        return "\n".join(L)

    # ── top-level emission ───────────────────────────────────────────────────
    def create_code(self):
        sm = self.sm
        bc_tags = sorted(sm._bc_source.boundary_conditions_list_dict.keys()) \
            if hasattr(sm, "_bc_source") else []
        blocks = [self._file_header(bc_tags)]

        ne, na, d = self.n_eq, self.n_aux, self.dim

        # flux / NCP / quasilinear (emitted for completeness; the C++ driver
        # reads these from Numerics.H, not from Model.H)
        fexpr, fshape = self._expr_flux()
        blocks.append(self._kernel("flux", fexpr, (fshape, 1), ("Q", "Qaux", "p")))
        blocks.append(self._kernel("dflux", self._zeros(ne * d), (ne * d, 1),
                                   ("Q", "Qaux", "p")))
        blocks.append(self._kernel("hydrostatic_pressure", self._zeros(ne * d),
                                   (ne * d, 1), ("Q", "Qaux", "p")))
        ncp, nshape = self._expr_matrix(sm.nonconservative_matrix)
        blocks.append(self._kernel("nonconservative_matrix", ncp, (nshape, 1),
                                   ("Q", "Qaux", "p")))
        ql, qshape = self._expr_matrix(sm.quasilinear_matrix)
        blocks.append(self._kernel("quasilinear_matrix", ql, (qshape, 1),
                                   ("Q", "Qaux", "p")))

        # diffusive_flux: zero stub (has_diffusion=false → never called, but the
        # symbol must exist: make_rhs.H references it in a non-template
        # `if constexpr` branch which is still fully type-checked).
        blocks.append(self._kernel("diffusive_flux", self._zeros(ne * d),
                                   (ne * d, 1), ("Q", "Qaux", "gradQ", "p")))

        # eigenvalues (depend on the face normal)
        eexpr, _ = self._expr_eigenvalues()
        if self.analytical_eigenvalues:
            blocks.append(self._kernel("eigenvalues", eexpr, (ne, 1),
                                       ("Q", "Qaux", "p", "n")))
        else:
            blocks.append(self._kernel("eigenvalues", self._zeros(ne), (ne, 1),
                                       ("Q", "Qaux", "p", "n")))
        blocks.append(self._kernel("left_eigenvectors", self._zeros(ne * ne),
                                   (ne * ne, 1), ("Q", "Qaux", "p", "n")))
        blocks.append(self._kernel("right_eigenvectors", self._zeros(ne * ne),
                                   (ne * ne, 1), ("Q", "Qaux", "p", "n")))

        # source + jacobians
        sexpr, _ = self._expr_source()
        blocks.append(self._kernel("source", sexpr, (ne, 1), ("Q", "Qaux", "p")))
        jexpr, _ = self._expr_source_jac()
        blocks.append(self._kernel("source_jacobian_wrt_variables", jexpr,
                                   (ne * ne, 1), ("Q", "Qaux", "p")))
        blocks.append(self._kernel("source_jacobian_wrt_aux_variables",
                                   self._zeros(ne * na), (ne * na, 1),
                                   ("Q", "Qaux", "p")))

        # 3d projection / misc (stubs; ZoomyAmr writes var0..varN directly)
        blocks.append(self._kernel("project_2d_to_3d", self._zeros(6), (6, 1),
                                   ("X", "Q", "Qaux", "p")))
        blocks.append(self._kernel("project_3d_to_2d", self._zeros(ne), (ne, 1),
                                   ("Q", "Qaux", "p")))
        blocks.append(self._kernel("residual", self._zeros(ne), (ne, 1),
                                   ("time", "X", "dX", "Q", "Qaux", "p")))
        blocks.append(self._kernel("interpolate", self._vec(list(sm.state)),
                                   (ne, 1), ("Q", "Qaux", "p")))
        blocks.append(self._kernel("initial_condition", self._zeros(ne), (ne, 1),
                                   ("X", "p")))
        blocks.append(self._kernel("initial_aux_condition", self._zeros(na),
                                   (na, 1), ("X", "p")))

        # update variables / aux + jacobians
        blocks.append(self._kernel("update_variables", self._vec(list(sm.state)),
                                   (ne, 1), ("Q", "Qaux", "p")))
        uaexpr, _ = self._expr_update_aux()
        blocks.append(self._kernel("update_aux_variables", uaexpr, (na, 1),
                                   ("Q", "Qaux", "p")))
        blocks.append(self._kernel("update_variables_jacobian_wrt_variables",
                                   self._identity_flat(ne), (ne * ne, 1),
                                   ("Q", "Qaux", "p")))
        blocks.append(self._kernel("update_aux_variables_jacobian_wrt_variables",
                                   self._zeros(na * ne), (na * ne, 1),
                                   ("Q", "Qaux", "p")))

        # boundary conditions — the real per-tag dispatch: ``sm.boundary_conditions``
        # is a framework ``Function`` whose ``.definition`` is a Piecewise over
        # ``bc_idx`` (the sorted-tag index) with a ghost-state vector per branch.
        # ``convert_expression_body`` lowers the Piecewise to an if/else-if chain;
        # ``bc_idx`` prints as itself (matches the C++ arg), Q/Qaux/n via the maps.
        bc_def = self._bc_definition("boundary_conditions")
        bc_expr = bc_def if bc_def is not None else self._vec(list(sm.state))
        blocks.append(self._kernel("boundary_conditions", bc_expr, (ne, 1),
                                   ("bc_idx", "Q", "Qaux", "n", "X", "time", "dX")))
        abc_def = self._bc_definition("aux_boundary_conditions")
        abc_expr = abc_def if abc_def is not None else (
            self._vec(list(sm.aux_state)) if na else self._zeros(0))
        blocks.append(self._kernel("aux_boundary_conditions", abc_expr, (na, 1),
                                   ("bc_idx", "Q", "Qaux", "n", "X", "time", "dX")))

        blocks.append("};\n")
        return "\n".join(blocks)


# ── user-functions helper header (opaque kernel bodies) ─────────────────────
USER_FUNCTIONS_H = """#pragma once
// Hand-written AMReX implementations of the opaque "kernel" placeholder
// functions (zoomy_core.model.kernel_functions).  The code printer emits
// `amrex_user::<name>(...)` calls; these are their device-side definitions.
// SWE/SME with a Rusanov flux does not invoke eigensystem / compute_derivative,
// so these are stubs until a Roe scheme or non-local aux is wired (task 0026).
#include <AMReX_REAL.H>
#include <AMReX_GpuQualifiers.H>

namespace amrex_user {

// Placeholder: a Roe-style eigensystem helper.  Returns its first argument.
template <typename T>
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE
T eigensystem(T a) noexcept { return a; }

// Placeholder: non-local spatial derivative (LSQ gradient) aux.  The driver
// supplies real gradients via Qaux; this opaque fallback returns 0.
template <typename T>
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE
T compute_derivative(T) noexcept { return T(0); }

}  // namespace amrex_user
"""


def generate_headers(sm, out_dir, *, riemann=None, analytical_eigenvalues=True):
    """Generate ``Model.H``, ``Numerics.H`` and ``UserFunctions.H`` into *out_dir*.

    Parameters
    ----------
    sm : SystemModel  (frozen, e.g. ``SWE(...).system_model``)
    out_dir : pathlib.Path
    riemann : a :class:`zoomy_core.fvm.riemann_solvers.Numerics` subclass; defaults
        to ``NonconservativeRusanov``.
    """
    from pathlib import Path
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    if riemann is None:
        from zoomy_core.fvm.riemann_solvers import NonconservativeRusanov
        riemann = NonconservativeRusanov
    num = riemann(model=sm)

    (out / "UserFunctions.H").write_text(USER_FUNCTIONS_H)
    (out / "Model.H").write_text(
        AmrexSystemModelPrinter(sm, analytical_eigenvalues=analytical_eigenvalues)
        .create_code())
    (out / "Numerics.H").write_text(AmrexNumericsPrinter(num).create_code())
    return out
